# -*- coding: utf-8 -*-
"""CRM .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dm7-VpDcA1czpkGmERYs52jvtd-aX6_O
"""

# src/crm.py
import pandas as pd
from data_loader_ import load_customer_data

class CRM:
    def __init__(self, data):
        self.data = data

    def get_customer_info(self, customer_id):
        customer = self.data[self.data['customer_id'] == customer_id]
        if not customer.empty:
            return customer.to_dict(orient='records')[0]
        else:
            return None

    def add_customer(self, customer_info):
        self.data = self.data.append(customer_info, ignore_index=True)

    def update_last_contacted(self, customer_id, date):
        self.data.loc[self.data['customer_id'] == customer_id, 'last_contacted'] = date

if __name__ == '__main__':
    df = load_customer_data('/content/customers.csv')
    crm = CRM(df)

    # Example operations
    print("Get Customer Info:")
    print(crm.get_customer_info(1))

    print("\nUpdate Last Contacted Date:")
    crm.update_last_contacted(1, '2023-07-04')
    print(crm.get_customer_info(1))