# -*- coding: utf-8 -*-
"""Data loader .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzbzQJocybtzSpejc-tIKyequ8R1tZ1l
"""

# src/data_loader.py
import pandas as pd

def load_customer_data(file_path):
    return pd.read_csv(file_path)

if __name__ == '__main__':
    df = load_customer_data('/content/customers.csv')
    print("Sample Customer Data:")
    print(df.head())