# -*- coding: utf-8 -*-
"""Reports.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgtOxTxI4lSESvVK7gloI4JDUIka10EW
"""

# src/reports.py
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from data_loader_ import load_customer_data

def generate_report(data):
    plt.figure(figsize=(10, 6))
    sns.countplot(x='company', data=data)
    plt.title('Number of Customers per Company')
    plt.xlabel('Company')
    plt.ylabel('Number of Customers')
    plt.savefig('/content/customers_per_company.png')
    plt.show()

if __name__ == '__main__':
    df = load_customer_data('/content/customers.csv')
    generate_report(df)